TrajectoryPlannerROS:
  acc_lim_x: 1.25
  acc_lim_y: 1.25
  acc_lim_theta: 1.25

  max_vel_x: 0.25
  min_vel_x: 0.15

  max_vel_theta: 0.25
  min_vel_theta: 0.05
  min_in_place_vel_theta: 0.15

  escape_vel: -0.25

  holonomic_robot: true
  y_vels: [-0.25, -0.15, 0.15, 0.25]
  
  sim_time: 1
  path_distance_bias: 0.8
  goal_distance_bias: 0.7
  vtheta_samples: 50
  occdist_scale: 0.05

  oscillation_reset_dist: 0.125

  